---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: trustify
  name: trustify
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: trustify
  name: trustify
rules:
  - apiGroups:
      - ""
      - "org.trustify"
      - "batch"
    resources:
      - '*'
    verbs:
      - '*'
  - apiGroups:
      - security.openshift.io
    resourceNames:
      - anyuid
    resources:
      - securitycontextconstraints
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: trustify
  name: trustify
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: trustify
subjects:
  - kind: ServiceAccount
    name: trustify
